### ISSUE TITLE
No rollback option for a task

### ISSUE THREAD

**Issue by Minal1409** [tbotnz/netpalm#23]
Please add rollback option for any task. This can be solved by two ways-
1. auto generating the delete config for service template which can be triggered when asked to rollback.
2. A rollback api can be developed which can just copy the rollback config to current running configuration device( generated during task execution by napalm)

**Comment by tbotnz** [comment]
Hi,

It would be best currently, to use the delete method in your service template,

Netpalm does not aim to store data for devices, would recommend doing this outside of netpalm

**Comment by nabapal** [comment]
napalm already have rollback feature. it can rollback the last session configuration change. can we not use this feature in netplam? it is useful when we need to perform multiple device configuration for a specific use case and one of the device configuration failed due to some reason and we need to rollback the other devices configuration to keep the provisioning status consistency.

**Comment by Minal1409** [comment]
Pls comment on if you are considering this as feature to be developed. As said by my friend we need this feature for the purpose above.
